### ISSUE TITLE
Pix2pix

### ISSUE THREAD

**Issue by SergeiVKalinin** [PacktPublishing/Hands-On-Image-Generation-with-TensorFlow-2.0#10]
Hello - when I try to run pix2pix, it gives error "    ValueError: Layer model_1 expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(1, 256, 256, 3) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(1, 256, 256, 3) dtype=float32>]"

**Comment by soon-yau** [comment]
Which Tensorflow version are you using? The code does not work for TF2.4 and above.

**Comment by SergeiVKalinin** [comment]
Thank you - fixed!
