### ISSUE TITLE
Why is Variational Autoencoder variance considered as a log-ed value?

### ISSUE THREAD

**Issue by luqmansrx** [PacktPublishing/Hands-On-Image-Generation-with-TensorFlow-2.0#11]
First of all, thank you for this book!

This might sound like a simple question but I can't understand why the returned variance values of the encoding space considered as log-ed as oppose to an un-log?

<img width="829" alt="Screenshot 2021-05-20 at 8 43 17 AM" src="https://user-images.githubusercontent.com/74533809/118902514-63ea1080-b948-11eb-83dd-3e75edfb6ac8.png">

Notebook: https://github.com/PacktPublishing/Hands-On-Image-Generation-with-TensorFlow-2.0/blob/master/Chapter02/ch2_vae_mnist.ipynb

**Comment by soon-yau** [comment]
Hi. The explanation is given in page 40 of the book, just underneath the code snippet of `GaussianSampling`

**Comment by luqmansrx** [comment]
Thanks for your reply. 

Sorry if it is still unclear to me and commenting after you close the issue. I was refering to the same page 40 line in the book.

> Note that we use log variance in the encoder space rather than variance for numerical stability.

However, I dont see how this variance that is returned from the Dense layer is log-treated. Do you assume after going through the Dense layer, without any activation function or treatment, that the value returned can be assumed to be log-treated?

I'll try to be abit clear in annotating,

`
class GaussianSampling(Layer):        
    def call(self, inputs):
        means, logvar = inputs  <--- not clear to me that logvar was log-treated. is it assumed?
        epsilon = tf.random.normal(shape=tf.shape(means), mean=0., stddev=1.)
        samples = means + tf.exp(0.5*logvar)*epsilon
        return samples

class Encoder(Layer):
    def __init__(self, z_dim, name='encoder'):
...
        self.dense_mean = Dense(z_dim, name='mean')
        self.dense_logvar = Dense(z_dim, name='logvar')   <-- this will give me any unbounded real number
        self.sampler = GaussianSampling()
        
    def call(self, inputs):
        x = self.features_extract(inputs)
        mean = self.dense_mean(x)
        logvar = self.dense_logvar(x)  <--  unbounded real number returned.
        z = self.sampler([mean, logvar]) <-- logvar is assumed to be log-treated?
        return z, mean, logvar`

<img width="821" alt="Screenshot 2021-05-20 at 5 06 20 PM" src="https://user-images.githubusercontent.com/74533809/118952950-f6ad9e00-b98e-11eb-812d-03dc1febf35e.png">

**Comment by soon-yau** [comment]
I may have misunderstood your question. Ok, now that you know why we use log variance and the question is why the output of `Dense` is log variance. 

That is because the dense layer is designed to learn to produce log variance, via GaussianSampling and KL divergence loss.

**Comment by luqmansrx** [comment]
Ah got it! thank you for your time to explain it.
