### ISSUE TITLE
Im very sorry for all the issues, found a great solution

### ISSUE THREAD

**Issue by dude123studios** [PacktPublishing/Hands-On-Image-Generation-with-TensorFlow-2.0#15]
replace the download of the celeb-a datast with:

import os
import tempfile
import urllib
gcs_base_dir = "gs://celeb_a_dataset/"
celeb_a_builder = tfds.builder("celeb_a", data_dir=gcs_base_dir, version='2.0.0')

celeb_a_builder.download_and_prepare()

num_test_shards_dict = {'0.3.0': 4, '2.0.0': 2} # Used because we download the test dataset separately
version = str(celeb_a_builder.info.version)
print('Celeb_A dataset version: %s' % version)

local_root = tempfile.mkdtemp(prefix='test-data')
def local_test_filename_base():
  return local_root

def local_test_file_full_prefix():
  return os.path.join(local_test_filename_base(), "celeb_a-test.tfrecord")

def copy_test_files_to_local():
  filename_base = local_test_file_full_prefix()
  num_test_shards = num_test_shards_dict[version]
  for shard in range(num_test_shards):
    url = "https://storage.googleapis.com/celeb_a_dataset/celeb_a/%s/celeb_a-test.tfrecord-0000%s-of-0000%s" % (version, shard, num_test_shards)
    filename = "%s-0000%s-of-0000%s" % (filename_base, shard, num_test_shards)
    res = urllib.request.urlretrieve(url, filename)

celeb_a_test_data = celeb_a_builder.as_dataset(split='test')
# Copy test data locally to be able to read it into tfma
copy_test_files_to_local()

**Comment by soon-yau** [comment]
Glad that you found a way that works with your system.
