### ISSUE TITLE
[ch4_pix2pix] Layer model_1 expects 1 input(s) 

### ISSUE THREAD

**Issue by RoastedKernel** [PacktPublishing/Hands-On-Image-Generation-with-TensorFlow-2.0#18]
`ValueError                                Traceback (most recent call last)
/tmp/ipykernel_676362/329867214.py in <module>
----> 1 pix2pix.train(iter(train_dataset), iter(test_dataset), BATCH_SIZE, 20000, 1000)

/tmp/ipykernel_676362/2401627389.py in train(self, data_generator, test_data_generator, batch_size, steps, interval)
    146 
    147             # train generator
--> 148             g_loss = self.model.train_on_batch([real_images_A, real_images_B], real_labels)
    149             if i%interval == 0:
    150                 msg = "Step {}: discriminator_loss {:.4f} g_loss {:.4f}"\

~/anaconda3/envs/gan/lib/python3.8/site-packages/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics, return_dict)
   1854                                                     class_weight)
   1855       self.train_function = self.make_train_function()
-> 1856       logs = self.train_function(iterator)
   1857 
   1858     if reset_metrics:

~/anaconda3/envs/gan/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    883 
    884       with OptionalXlaContext(self._jit_compile):
--> 885         result = self._call(*args, **kwds)
    886 
    887       new_tracing_count = self.experimental_get_tracing_count()

~/anaconda3/envs/gan/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    931       # This is the first call of __call__, so we have to initialize.
    932       initializers = []
--> 933       self._initialize(args, kwds, add_initializers_to=initializers)
    934     finally:
    935       # At this point we know that the initialization is complete (or less

~/anaconda3/envs/gan/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    757     self._graph_deleter = FunctionDeleter(self._lifted_initializer_graph)
    758     self._concrete_stateful_fn = (
--> 759         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
    760             *args, **kwds))
    761 

~/anaconda3/envs/gan/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   3064       args, kwargs = None, None
   3065     with self._lock:
-> 3066       graph_function, _ = self._maybe_define_function(args, kwargs)
   3067     return graph_function
   3068 

~/anaconda3/envs/gan/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3461 
   3462           self._function_cache.missed.add(call_context_key)
-> 3463           graph_function = self._create_graph_function(args, kwargs)
   3464           self._function_cache.primary[cache_key] = graph_function
   3465 

~/anaconda3/envs/gan/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3296     arg_names = base_arg_names + missing_arg_names
   3297     graph_function = ConcreteFunction(
-> 3298         func_graph_module.func_graph_from_py_func(
   3299             self._name,
   3300             self._python_function,

~/anaconda3/envs/gan/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes, acd_record_initial_resource_uses)
   1005         _, original_func = tf_decorator.unwrap(python_func)
   1006 
-> 1007       func_outputs = python_func(*func_args, **func_kwargs)
   1008 
   1009       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/anaconda3/envs/gan/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    666         # the function a weak reference to itself to avoid a reference cycle.
    667         with OptionalXlaContext(compile_with_xla):
--> 668           out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    669         return out
    670 

~/anaconda3/envs/gan/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    992           except Exception as e:  # pylint:disable=broad-except
    993             if hasattr(e, "ag_error_metadata"):
--> 994               raise e.ag_error_metadata.to_exception(e)
    995             else:
    996               raise

ValueError: in user code:

    /home/roastedkernel/anaconda3/envs/gan/lib/python3.8/site-packages/keras/engine/training.py:853 train_function  *
        return step_function(self, iterator)
    /home/roastedkernel/anaconda3/envs/gan/lib/python3.8/site-packages/keras/engine/training.py:842 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /home/roastedkernel/anaconda3/envs/gan/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/roastedkernel/anaconda3/envs/gan/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/roastedkernel/anaconda3/envs/gan/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/roastedkernel/anaconda3/envs/gan/lib/python3.8/site-packages/keras/engine/training.py:835 run_step  **
        outputs = model.train_step(data)
    /home/roastedkernel/anaconda3/envs/gan/lib/python3.8/site-packages/keras/engine/training.py:787 train_step
        y_pred = self(x, training=True)
    /home/roastedkernel/anaconda3/envs/gan/lib/python3.8/site-packages/keras/engine/base_layer.py:1020 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /home/roastedkernel/anaconda3/envs/gan/lib/python3.8/site-packages/keras/engine/input_spec.py:199 assert_input_compatibility
        raise ValueError('Layer ' + layer_name + ' expects ' +

    ValueError: Layer model_1 expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(4, 256, 256, 3) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(4, 256, 256, 3) dtype=float32>]`

**Comment by RoastedKernel** [comment]
this is on TensorFlow 2.6. cant run on TensorFlow 2.2 due to TF2.2 cuda version isnt supported on my gpu.

**Comment by soon-yau** [comment]
@RoastedKernel I have pushed a fix to the master branch.

**Comment by RoastedKernel** [comment]
fixed thanks and  great book by the way.

**Comment by soon-yau** [comment]
> fixed thanks and great book by the way.

Thanks, glad to hear that. If you can, please write a book review on Amazon.
