### ISSUE TITLE
Chapter 1 - ch1_generate_first_image - Loading images

### ISSUE THREAD

**Issue by moodmap** [PacktPublishing/Hands-On-Image-Generation-with-TensorFlow-2.0#3]
When I attempt to run the line - ds_train, ds_info = tfds.load('celeb_a', split='test', shuffle_files=False, with_info=True)

I get the following error:

"NonMatchingChecksumError                  Traceback (most recent call last)

NonMatchingChecksumError: Artifact https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM, downloaded to C:\...\ucexport_download_id_0B7EVK8r0v71pZjFTYXZWM3FlDDaXUAQO8EGH_a7VqGNLRtW52mva1LzDrb-V723OQN8.tmp.521a68dd559d4cd49b06809e3e944c38\uc, has wrong checksum. Expected: UrlInfo(size=1.34 GiB, checksum='46fb89443c578308acf364d7d379fe1b9efb793042c0af734b6112e4fd3a8c74', filename='img_align_celeba.zip'). Got: UrlInfo(size=3.02 KiB, checksum='7871bf45999c9dfc0e6c0ebc60f44e77e6add3cdc9eee3072489754587b2a6f6', filename='uc').To debug, see: https://www.tensorflow.org/datasets/overview#fixing_nonmatchingchecksumerror"

**Comment by soon-yau** [comment]
This is due to Google's limiting download from their server. There was instruction in ch2_vae_celeb to download the dataset manually. I have now also copied that to ch1_generate_first_image, please git pull to get that change.

**Comment by dude123studios** [comment]
When I run the code in google colab it gives me a FileNotFoundError on the gdown.download line. I don't know what I'm doing wrong.

**Comment by GersomR-afk** [comment]
> When I run the code in google colab it gives me a FileNotFoundError on the gdown.download line. I don't know what I'm doing wrong.

@soon-yau
