### ISSUE TITLE
Chapter 8 BigGAN error in Orthogonal 

### ISSUE THREAD

**Issue by baniasbaabe** [PacktPublishing/Hands-On-Image-Generation-with-TensorFlow-2.0#6]
![image](https://user-images.githubusercontent.com/72874670/110931783-f491e800-832a-11eb-8b43-4e751a68dd76.png)

**Comment by baniasbaabe** [comment]
When I run the cell with the OrthogonalRegularizer, I always get this error message.

**Comment by soon-yau** [comment]
It works fine with Tensorflow 2.2.0. What version did you use? 
Blas is linear algebra library but I'd expect Nvidia's cuBLAS to be used. It may be that cublas has not been installed correctly.
One thing you can try is to disable GPU by changing this line on top of the notebook 
`tf.config.experimental.set_visible_devices(gpus[0], 'GPU')`
to 
`tf.config.experimental.set_visible_devices([], 'GPU')`

Alternatively, try this on Google Colab but be sure to install the correct Tensorflow version.
