### ISSUE TITLE
Stylegan: InvalidArgumentError

### ISSUE THREAD

**Issue by baniasbaabe** [PacktPublishing/Hands-On-Image-Generation-with-TensorFlow-2.0#7]
When you train the Stylegan with a Resolution of 1024, you get an error when the model expands to 1024:

`InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs, op_def)
   1653   try:
-> 1654     c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
   1655   except errors.InvalidArgumentError as e:

InvalidArgumentError: slice index 8 of dimension 1 out of bounds. for '{{node strided_slice_8}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=1, ellipsis_mask=0, end_mask=1, new_axis_mask=0, shrink_axis_mask=2](input_2, strided_slice_8/begin, strided_slice_8/end, strided_slice_8/strides)' with input shapes: [?,8,512], [2], [2], [2] and with computed input tensors: input[1] = <0 8>, input[2] = <0 9>, input[3] = <1 1>.

in grow_generator(self, log2_res)
    268 
    269         x = self.generator_blocks[log2_res]([x, 
--> 270                                              w[:,log2_res-2],
    271                                              self.noise_inputs[log2_res]])
    272         print(f"grow_generator end, log2={log2_res} w={log2_res-2}, noise={log2_res}", )

`

Should you do log2_res - 1 instead of - 2?

**Comment by baniasbaabe** [comment]
When you do log2_res - 3, instead of - 2, it works, but I don't know if this is the right approach :)

**Comment by soon-yau** [comment]
Hi Banias

Can you try to change line 250 to
`w = Input(shape=(9, 512))`

**Comment by baniasbaabe** [comment]
Yes, this helped. Thanks :)
