### ISSUE TITLE
Restart training Attribute Error

### ISSUE THREAD

**Issue by baniasbaabe** [PacktPublishing/Hands-On-Image-Generation-with-TensorFlow-2.0#9]
If you want to retrain the StyleGAN model with saved weights like this

gan = StyleGAN(resolution=IMAGE_RESOLUTION, load_path='./checkpoints/stylegan-29042021', start_log2_res=10)

You get following output:

Growing model to 1024x1024
grow_generator mid, log2=3 w=1, noise=3
grow_generator mid, log2=4 w=2, noise=4
grow_generator mid, log2=5 w=3, noise=5
grow_generator mid, log2=6 w=4, noise=6
grow_generator mid, log2=7 w=5, noise=7
grow_generator mid, log2=8 w=6, noise=8
grow_generator mid, log2=9 w=7, noise=9
grow_generator end, log2=10 w=8, noise=10

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-ab3b69d4278b> in <module>
----> 1 gan = StyleGAN(resolution=IMAGE_RESOLUTION, load_path='./checkpoints/stylegan-29042021', start_log2_res=10)

<ipython-input-22-c4fc7bab3725> in __init__(self, z_dim, resolution, load_path, start_log2_res)
     28 
     29         if load_path:
---> 30             self.load_checkpoint(load_path)
     31 
     32         # initialize generator with the base

<ipython-input-22-c4fc7bab3725> in load_checkpoint(self, ckpt_path)
     77     def load_checkpoint(self, ckpt_path):
     78         self.grow_model(self.start_log2_res)
---> 79         self.ckpt.restore(ckpt_path)
     80 
     81 

AttributeError: 'StyleGAN' object has no attribute 'ckpt'

**Comment by baniasbaabe** [comment]
Its very weird because the self.ckpt variable is not visible somehow

**Comment by baniasbaabe** [comment]
![grafik](https://user-images.githubusercontent.com/72874670/116856167-f4132080-abfa-11eb-97c2-217739538180.png)

my files are like this

**Comment by baniasbaabe** [comment]
If you change the order in the __init__ to:

checkpoint_path = f"./checkpoints/stylegan-29042021/"
        self.ckpt = tf.train.Checkpoint(generator = self.generator, discriminator = self.discriminator)
        self.ckpt_manager = tf.train.CheckpointManager(self.ckpt, checkpoint_path, max_to_keep = 40)
        if load_path:
            self.load_checkpoint(load_path)

Then the error disappears but a know error comes:

Growing model to 1024x1024
grow_generator mid, log2=3 w=1, noise=3
grow_generator mid, log2=4 w=2, noise=4
grow_generator mid, log2=5 w=3, noise=5
grow_generator mid, log2=6 w=4, noise=6
grow_generator mid, log2=7 w=5, noise=7
grow_generator mid, log2=8 w=6, noise=8
grow_generator mid, log2=9 w=7, noise=9
grow_generator end, log2=10 w=8, noise=10

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\gputest\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py in NewCheckpointReader(filepattern)
     94   try:
---> 95     return CheckpointReader(compat.as_bytes(filepattern))
     96   # TODO(b/143319754): Remove the RuntimeError casting logic once we resolve the

RuntimeError: Unable to open table file .\checkpoints: Unknown: NewRandomAccessFile failed to Create/Open: .\checkpoints : Zugriff verweigert
; Input/output error

During handling of the above exception, another exception occurred:

DataLossError                             Traceback (most recent call last)
<ipython-input-18-4c0d22d78ac5> in <module>
----> 1 gan = StyleGAN(resolution=IMAGE_RESOLUTION, load_path='./checkpoints', start_log2_res=10)

<ipython-input-17-012f63d71b56> in __init__(self, z_dim, resolution, load_path, start_log2_res)
     68         self.ckpt_manager = tf.train.CheckpointManager(self.ckpt, checkpoint_path, max_to_keep = 40)
     69         if load_path:
---> 70             self.load_checkpoint(load_path)
     71 
     72     def load_checkpoint(self, ckpt_path):

<ipython-input-17-012f63d71b56> in load_checkpoint(self, ckpt_path)
     72     def load_checkpoint(self, ckpt_path):
     73         self.grow_model(self.start_log2_res)
---> 74         self.ckpt.restore(ckpt_path)
     75 
     76 

C:\ProgramData\Anaconda3\envs\gputest\lib\site-packages\tensorflow\python\training\tracking\util.py in restore(self, save_path)
   2007           (often at program shutdown).
   2008     """
-> 2009     status = self._saver.restore(save_path=save_path)
   2010     # Create the save counter now so it gets initialized with other variables
   2011     # when graph building. Creating it earlier would lead to errors when using,

C:\ProgramData\Anaconda3\envs\gputest\lib\site-packages\tensorflow\python\training\tracking\util.py in restore(self, save_path)
   1258     if save_path is None:
   1259       return InitializationOnlyStatus(self._graph_view, ops.uid())
-> 1260     reader = py_checkpoint_reader.NewCheckpointReader(save_path)
   1261     graph_building = not context.executing_eagerly()
   1262     if graph_building:

C:\ProgramData\Anaconda3\envs\gputest\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py in NewCheckpointReader(filepattern)
     97   # issue with throwing python exceptions from C++.
     98   except RuntimeError as e:
---> 99     error_translator(e)

C:\ProgramData\Anaconda3\envs\gputest\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py in error_translator(e)
     42     raise errors_impl.InvalidArgumentError(None, None, error_message)
     43   elif 'Unable to open table file' in error_message:
---> 44     raise errors_impl.DataLossError(None, None, error_message)
     45   elif 'Failed to find the saved tensor slices' in error_message:
     46     raise errors_impl.InternalError(None, None, error_message)

DataLossError: Unable to open table file .\checkpoints: Unknown: NewRandomAccessFile failed to Create/Open: .\checkpoints : Zugriff verweigert
; Input/output error


Zugriff verweigert means "access denied"

**Comment by soon-yau** [comment]
Apologies, I never got the checkpoints to work but forgot to remove it. The reason is a little complicated. Keras checkpoint doesn't allow to save a list of model but unfortunately what I used for `to_rgb` . 

My workaround was to save the individual model separately, if you scroll toward the bottom of the notebook, you will see this
![save](https://user-images.githubusercontent.com/19167278/117076471-591b6300-ad2e-11eb-855d-e18332b0a536.png)
However, I only used it to save the models after finish training but did not incorporate it into the training pipeline. Therefore, I'm afraid you can't use the checkpoints that you have saved.

**Comment by soon-yau** [comment]
I have now pushed the code to save checkpoints but you'll have to start the training from scratch.

**Comment by baniasbaabe** [comment]
Nice thank you Sir:) But theoretically, you can use instantiate a new StyleGAN-object with start_log2res = 9, use your workaround :

![grafik](https://user-images.githubusercontent.com/72874670/117114725-7f6feb80-ad8c-11eb-87f7-4a53e94353e6.png)

And then restart training. This would also works or not?

**Comment by soon-yau** [comment]
If the models are still in the notebook (you haven't stop/reset after training), then yes, you can use that to save the models. But that code only save up to log2_res = 8 i.e. resolution 256. Increase is to 11 to save 1024.

You can also use new code `load_checkpoint(path)` to load it. It will automatically load and rebuild the model to the highest resolution saved in the checkpoint.

**Comment by baniasbaabe** [comment]
Thanks I will check it out :)
